### ISSUE TITLE
log ip remover repo

### ISSUE THREAD

**Issue by Oregano1963** [Ayydxn/Iridium#1]
this isn't related to your vulkan project but you formerly had a repo of the log ip remover mod but the link leads nowhere. I remember it used to be available on Modrinth and I even had a copy myself but no longer do. When I tried to find it again recently, it was gone. If you still have a copy of that jar, could you send it to me and do you know what happened to the mod? Every Github repo with that name no longer exists.

link: https://github.com/Ayydxn/LogIPRemover

**Comment by worldwidepixel** [comment]
How on earth did I get a notification for this?

**Comment by Oregano1963** [comment]
that's odd

**Comment by Ayydxn** [comment]
> this isn't related to your vulkan project but you formerly had a repo of the log ip remover mod but the link leads nowhere. I remember it used to be available on Modrinth and I even had a copy myself but no longer do. When I tried to find it again recently, it was gone. If you still have a copy of that jar, could you send it to me and do you know what happened to the mod? Every Github repo with that name no longer exists.
> 
> link: https://github.com/Ayydxn/LogIPRemover

I decided to just stop maintaining the mod and bothering with it all together a few months ago as it just became annoying for me. Not because there was a bunch of technical issues or anything, but rather because there was other projects I'd rather work on than spend like 15 minutes updating it and publishing the updated version. As for its source code, I don't have an archive of it myself, but I do remember how I implemented it.

**Comment by Oregano1963** [comment]
How was it implemented?

**Comment by Oregano1963** [comment]
And I guess it'd be important to know: are you the original mod maker?

**Comment by Ayydxn** [comment]
Yes, I am the original creator of the mod, and it was implemented by having a mixin with PlayerManager's onPlayerConnect function that changed the string passed to the LOGGER.info call depending if hiding IPs was enabled in the mod's config or not.

![image](https://github.com/user-attachments/assets/38b39bfa-4017-4afa-9a99-0e3ec78b14cb)

**Comment by Oregano1963** [comment]
Interesting. Though this mod (I found a copy on my old laptop) didn't hide my IP from Aternos.

**Comment by Ayydxn** [comment]
Well, it appears that the game now has the exactly same thing already built in. So, you should use that instead.

**Comment by Oregano1963** [comment]
how would I enable that? The bast 1.21.0 doesn't hide IPs
